language: node_jd
sudo: required
before_install:
- docker login -u"$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t kuribohw/htmltest .
- docker push kuribohw/htmltest
after_succcess:
- docker run -p 8088:80 -d kuribohw/htmltest:latest
service: docker
